obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SAMSUNG_LTE430WQ_F0C) += panel-samsung-lte430wq-f0c.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_LQ043T1DG01) += panel-sharp-lq043t1dg01.o
obj-$(CONFIG_PANEL_DEVKIT8500) += panel-omap3-devkit8500.o
obj-$(CONFIG_PANEL_DM3730_EVK) += panel-dm3730_evk.o
obj-$(CONFIG_PANEL_SBC8510) += panel-omap3-sbc8510.o
obj-$(CONFIG_PANEL_SBC8100_PLUS) += panel-omap3-sbc8100_plus.o
obj-$(CONFIG_PANEL_SBC8530) += panel-omap3-sbc8530.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
