# OMAP Platform Support
snd-soc-omap-objs := omap-pcm.o
snd-soc-omap-mcbsp-objs := omap-mcbsp.o

obj-$(CONFIG_SND_OMAP_SOC) += snd-soc-omap.o
obj-$(CONFIG_SND_OMAP_SOC_MCBSP) += snd-soc-omap-mcbsp.o

# OMAP Machine Support
snd-soc-n810-objs := n810.o
snd-soc-ams-delta-objs := ams-delta.o
snd-soc-osk5912-objs := osk5912.o
snd-soc-overo-objs := overo.o
snd-soc-omap2evm-objs := omap2evm.o
snd-soc-omap3evm-objs := omap3evm.o
snd-soc-am3517evm-objs := am3517evm.o
snd-soc-sdp3430-objs := sdp3430.o
snd-soc-omap3pandora-objs := omap3pandora.o
snd-soc-omap3beagle-objs := omap3beagle.o
snd-soc-omap3devkit8500-objs := omap3devkit8500.o
snd-soc-dm3730_evk-objs := dm3730_evk.o
snd-soc-omap3sbc8510-objs := omap3sbc8510.o
snd-soc-omap3sbc8100_plus-objs := omap3sbc8100_plus.o
snd-soc-omap3sbc8150-objs := omap3sbc8150.o
snd-soc-omap3sbc8530-objs := omap3sbc8530.o
snd-soc-zoom2-objs := zoom2.o
snd-soc-igep0020-objs := igep0020.o

obj-$(CONFIG_SND_OMAP_SOC_N810) += snd-soc-n810.o
obj-$(CONFIG_SND_OMAP_SOC_AMS_DELTA) += snd-soc-ams-delta.o
obj-$(CONFIG_SND_OMAP_SOC_OSK5912) += snd-soc-osk5912.o
obj-$(CONFIG_SND_OMAP_SOC_OVERO) += snd-soc-overo.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP2EVM) += snd-soc-omap2evm.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3EVM) += snd-soc-omap3evm.o
obj-$(CONFIG_SND_OMAP_SOC_AM3517EVM) += snd-soc-am3517evm.o
obj-$(CONFIG_SND_OMAP_SOC_SDP3430) += snd-soc-sdp3430.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_PANDORA) += snd-soc-omap3pandora.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_BEAGLE) += snd-soc-omap3beagle.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_DEVKIT8500) += snd-soc-omap3devkit8500.o
obj-$(CONFIG_SND_OMAP_SOC_DM3730_EVK) += snd-soc-dm3730_evk.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_SBC8510) += snd-soc-omap3sbc8510.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_SBC8100_PLUS) += snd-soc-omap3sbc8100_plus.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_SBC8150) += snd-soc-omap3sbc8150.o
obj-$(CONFIG_SND_OMAP_SOC_OMAP3_SBC8530) += snd-soc-omap3sbc8530.o
obj-$(CONFIG_SND_OMAP_SOC_ZOOM2) += snd-soc-zoom2.o
obj-$(CONFIG_SND_OMAP_SOC_IGEP0020) += snd-soc-igep0020.o
